### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by miniBill** [wolfadex/elm-open-api-cli#112]
We currently have:
`name` - `Cmd`
`nameTask` - `Task`
`nameBackendTask` - `BackendTask`
`nameEffect` - `Command` (lamdera/program-test)

And all the `risky` variants. If we add `avh/elm-program-test` this is probably going to become unwieldy.

Proposal: multiple modules.
If there is a single package just use `Cmd`/`Task` in `Module.Api`
If there are multiple packages just use `Cmd`/`Task` in `Module.Api.Package`

So, current users are unaffected, and users with multiple types will get things like:

`Github.Api.ElmHttp.getStarsTask`
`Github.Api.Avh4ElmProgramTest.getStarsTask`

Instead of having to invent a new suffix for each package and type combination.

**Comment by wolfadex** [comment]
This is definitely worth it I think. Especially that it doesn't change anything for basic users.
