### ISSUE TITLE
Support for lenient decoding

### ISSUE THREAD

**Issue by pete-murphy** [wolfadex/elm-open-api-cli#64]
I don't know if anyone else has a use for this, but I am working with an internal Open API spec that apparently is not completely valid according to the spec. Out of hundreds of endpoints, there were a handful with empty `responses` objects (so the JSON would contain literally `"responses":{}`). I didn't really care about the offending endpoints, so in order to keep just the good ones, I ended up vendoring this project and the `elm-open-api` project with a modified decoder for `"paths"` that just filters out the malformed endpoints.
https://github.com/pete-murphy/elm-open-api-cli/blob/95e76eec0399f573037450d6beecd0b958664b1e/src/OpenApi.elm#L111-L126
I figured I'd share in case anyone else has a similar issue, though I don't have any idea about how the API for this tool could have been extended to support my use case, or if anyone would even want that.

**Comment by miniBill** [comment]
Could you possibly clean up the json with a pre-pass on it? Like, a decoder that produces json and filters out those broken endpoints 🤔

**Comment by wolfadex** [comment]
I think I'm going to adhere to the Open API spec here

> The Responses Object MUST contain at least one response code, and if only one response code is provided it SHOULD be the response for a successful operation call.

as this is being parsed by https://package.elm-lang.org/packages/wolfadex/elm-open-api/latest/ and I'd like that to adhere to the spec as much as possible.
