### ISSUE TITLE
Some definitions fail to generate correctly in generated output

### ISSUE THREAD

**Issue by jamesrweb** [wolfadex/elm-open-api-cli#65]
When generating the `SpaceTraders` API from their spec, the generated output is invalid. For example some types have no definitions.

Command:

```sh
elm-open-api \"https://stoplight.io/api/v1/projects/spacetraders/spacetraders/nodes/reference/SpaceTraders.json?fromExportButton=true&snapshotType=http_service&deref=optimizedBundle\" --output-dir src --module-name \"Generated.SpacetradersApi\" --generateTodos true
```

Example of the issue:
![Screenshot 2024-03-31 223317](https://github.com/wolfadex/elm-open-api-cli/assets/47126579/f0e114cd-36bd-4db7-bfc3-79e49f1f5a8c)

~~Also there are cases such as `type alias ActivityLevel = String` but this type should be limited to the 4 valid values `WEAK`, `GROWING`, `STRONG`, `RESTRICTED` [as documented in the spec](https://spacetraders.stoplight.io/docs/spacetraders/ed1a7d57959d3-activity-level).~~ - Striked out as this is an issue with their own types in the spec.

Notes:

No errors are thrown during generation but warnings about `Warning: Error! Multiple security requirements` but this is expected? I suppose this is something being worked on still, or what's the plan for security topics?

**Comment by jamesrweb** [comment]
I also see that cases such as [Agent](https://spacetraders.stoplight.io/docs/spacetraders/db315e27786ad-agent) and their related validations are not correctly generated also, for example lengths or ranges don't seem to be tested, only that the field exists.

**Comment by wolfadex** [comment]
This should be resolved by #80

**Comment by wolfadex** [comment]
> I also see that cases such as [Agent](https://spacetraders.stoplight.io/docs/spacetraders/db315e27786ad-agent) and their related validations are not correctly generated also, for example lengths or ranges don't seem to be tested, only that the field exists.

Moving this to it's own issue as it seems worth discussing more, and it separate from bad code gen.

**Comment by jamesrweb** [comment]
Works like a charm 👍🏻!
